[package]
name = "stevia"
version = "0.1.0"
authors = ["Robbepop <robbepop@web.de>"]

[dependencies]
smt-expr-derive = { path = "smt-expr-derive" }
smallvec = "0.3.3"
unreachable = "1.0.0"
itertools = "0.6.0"
string-interner = "0.3.3"
